task:
  name: hello
  macos_instance:
    # can be a remote or a local virtual machine
    image: sonoma-xcode-nix:15.2
  buildmobile_script:
    - sudo launchctl kickstart -k system/org.nixos.nix-daemon
    - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    - nix develop --impure --accept-flake-config
    - rm -rf .nx
    - rm -rf node_modules
    - yarn install
    - pushd apps/mobile
    - bundle
    - popd
    # - npx react-native doctor
    - yarn nx pod-install mobile
    # - yarn nx build-ios mobile
    - chmod 755 apps/mobile/android/gradlew
    - yarn nx build-android mobile
    - sleep 15
