task:
  name: hello
  macos_instance:
    # can be a remote or a local virtual machine
    image: sonoma-xcode-nix:15.2
  hello_script:
    - sudo launchctl kickstart -k system/org.nixos.nix-daemon
    - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    - brew install direnv
    - direnv allow
    - yarn install
    - pushd apps/mobile
    - bundle
    - popd
    - yarn nx pod-install mobile
    - yarn nx build-android mobile
    - yarn nx build-ios mobile
    - sleep 15
